// ********RoostGPT********
/*
Test generated by RoostGPT for test trivy-scan-mock using AI Type Claude AI and AI Model claude-3-5-sonnet-20240620

ROOST_METHOD_HASH=excludePackages_d68199d8c7
ROOST_METHOD_SIG_HASH=excludePackages_62917a217c

FUNCTION_DEF=func excludePackages(target *types.ScanTarget, options types.ScanOptions)
Based on the provided function `excludePackages` and the associated types and imports, I'll generate test scenarios to cover various aspects of its functionality. Here are the test scenarios:

```
Scenario 1: Exclude packages based on relationship

Details:
  Description: This test verifies that the function correctly filters packages based on the specified relationships in the ScanOptions.

Execution:
  Arrange:
    - Create a ScanTarget with a mix of packages having different relationships
    - Set up ScanOptions with specific PkgRelationships
  Act:
    - Call excludePackages(target, options)
  Assert:
    - Verify that only packages with relationships specified in options.PkgRelationships remain in the target

Validation:
  This test is crucial to ensure that the function correctly applies the relationship filter, which is important for focusing the scan on relevant packages based on user preferences.

Scenario 2: Exclude dev dependencies when IncludeDevDeps is false

Details:
  Description: This test checks if the function correctly excludes development dependencies when IncludeDevDeps option is set to false.

Execution:
  Arrange:
    - Create a ScanTarget with Applications containing both regular and dev dependencies
    - Set up ScanOptions with IncludeDevDeps set to false
  Act:
    - Call excludePackages(target, options)
  Assert:
    - Verify that dev dependencies are removed from the Applications in the target

Validation:
  This test ensures that the function respects the IncludeDevDeps option, which is important for users who want to focus only on production dependencies.

Scenario 3: Include all packages when no filtering options are set

Details:
  Description: This test verifies that the function doesn't exclude any packages when no filtering options are specified.

Execution:
  Arrange:
    - Create a ScanTarget with a variety of packages and applications
    - Set up ScanOptions with empty PkgRelationships and IncludeDevDeps set to true
  Act:
    - Call excludePackages(target, options)
  Assert:
    - Verify that all original packages and applications remain unchanged in the target

Validation:
  This test is important to ensure that the function doesn't inadvertently filter packages when no exclusion is intended.

Scenario 4: Handle empty ScanTarget

Details:
  Description: This test checks how the function behaves when given an empty ScanTarget.

Execution:
  Arrange:
    - Create an empty ScanTarget
    - Set up ScanOptions with some filtering options
  Act:
    - Call excludePackages(target, options)
  Assert:
    - Verify that the function doesn't panic and the target remains empty

Validation:
  This test ensures that the function gracefully handles edge cases like empty input, which is important for robustness.

Scenario 5: Exclude packages with multiple relationship filters

Details:
  Description: This test verifies that the function correctly applies multiple relationship filters simultaneously.

Execution:
  Arrange:
    - Create a ScanTarget with packages having various relationships
    - Set up ScanOptions with multiple PkgRelationships (e.g., Direct and Indirect)
  Act:
    - Call excludePackages(target, options)
  Assert:
    - Verify that only packages with relationships matching any in the options remain

Validation:
  This test is important to ensure that the function can handle complex filtering scenarios, allowing users to specify multiple relationship types to include.

Scenario 6: Preserve non-package data in ScanTarget

Details:
  Description: This test checks that the function only modifies package-related data and preserves other information in the ScanTarget.

Execution:
  Arrange:
    - Create a ScanTarget with packages, applications, and other data (e.g., OS, Repository, Misconfigurations)
    - Set up ScanOptions with some filtering criteria
  Act:
    - Call excludePackages(target, options)
  Assert:
    - Verify that non-package related data in the target remains unchanged

Validation:
  This test ensures that the function's scope is limited to package filtering and doesn't inadvertently modify other important scan data.
```

These test scenarios cover various aspects of the `excludePackages` function, including normal operation, edge cases, and different configuration options. They aim to ensure that the function correctly filters packages based on relationships and development dependencies while maintaining the integrity of other data in the ScanTarget.
*/

// ********RoostGPT********
package local

import (
	"reflect"
	"testing"

	ftypes "github.com/aquasecurity/trivy/pkg/fanal/types"
	"github.com/aquasecurity/trivy/pkg/types"
)

func TestExcludePackages(t *testing.T) {
	tests := []struct {
		name    string
		target  *types.ScanTarget
		options types.ScanOptions
		want    *types.ScanTarget
	}{
		{
			name: "Exclude packages based on relationship",
			target: &types.ScanTarget{
				Packages: []ftypes.Package{
					{Name: "pkg1", Relationship: ftypes.RelationshipDirect},
					{Name: "pkg2", Relationship: ftypes.RelationshipIndirect},
					{Name: "pkg3", Relationship: ftypes.RelationshipDirect},
				},
			},
			options: types.ScanOptions{
				PkgRelationships: []ftypes.Relationship{ftypes.RelationshipDirect},
			},
			want: &types.ScanTarget{
				Packages: []ftypes.Package{
					{Name: "pkg1", Relationship: ftypes.RelationshipDirect},
					{Name: "pkg3", Relationship: ftypes.RelationshipDirect},
				},
			},
		},
		{
			name: "Exclude dev dependencies",
			target: &types.ScanTarget{
				Applications: []ftypes.Application{
					{
						Type: ftypes.Bundler,
						Packages: []ftypes.Package{
							{Name: "lib1", Relationship: ftypes.RelationshipDirect},
							{Name: "lib2", Relationship: ftypes.RelationshipIndirect},
							{Name: "lib3", Relationship: ftypes.RelationshipDirect, Dev: true},
						},
					},
				},
			},
			options: types.ScanOptions{
				IncludeDevDeps: false,
			},
			want: &types.ScanTarget{
				Applications: []ftypes.Application{
					{
						Type: ftypes.Bundler,
						Packages: []ftypes.Package{
							{Name: "lib1", Relationship: ftypes.RelationshipDirect},
							{Name: "lib2", Relationship: ftypes.RelationshipIndirect},
						},
					},
				},
			},
		},
		{
			name: "Include all packages when no filtering options are set",
			target: &types.ScanTarget{
				Packages: []ftypes.Package{
					{Name: "pkg1", Relationship: ftypes.RelationshipDirect},
					{Name: "pkg2", Relationship: ftypes.RelationshipIndirect},
				},
				Applications: []ftypes.Application{
					{
						Type: ftypes.Npm,
						Packages: []ftypes.Package{
							{Name: "lib1", Relationship: ftypes.RelationshipDirect},
							{Name: "lib2", Relationship: ftypes.RelationshipDirect, Dev: true},
						},
					},
				},
			},
			options: types.ScanOptions{
				IncludeDevDeps: true,
			},
			want: &types.ScanTarget{
				Packages: []ftypes.Package{
					{Name: "pkg1", Relationship: ftypes.RelationshipDirect},
					{Name: "pkg2", Relationship: ftypes.RelationshipIndirect},
				},
				Applications: []ftypes.Application{
					{
						Type: ftypes.Npm,
						Packages: []ftypes.Package{
							{Name: "lib1", Relationship: ftypes.RelationshipDirect},
							{Name: "lib2", Relationship: ftypes.RelationshipDirect, Dev: true},
						},
					},
				},
			},
		},
		{
			name:    "Handle empty ScanTarget",
			target:  &types.ScanTarget{},
			options: types.ScanOptions{},
			want:    &types.ScanTarget{},
		},
		{
			name: "Exclude packages with multiple relationship filters",
			target: &types.ScanTarget{
				Packages: []ftypes.Package{
					{Name: "pkg1", Relationship: ftypes.RelationshipDirect},
					{Name: "pkg2", Relationship: ftypes.RelationshipIndirect},
					{Name: "pkg3", Relationship: ftypes.RelationshipRoot},
				},
			},
			options: types.ScanOptions{
				PkgRelationships: []ftypes.Relationship{ftypes.RelationshipDirect, ftypes.RelationshipIndirect},
			},
			want: &types.ScanTarget{
				Packages: []ftypes.Package{
					{Name: "pkg1", Relationship: ftypes.RelationshipDirect},
					{Name: "pkg2", Relationship: ftypes.RelationshipIndirect},
				},
			},
		},
		{
			name: "Preserve non-package data in ScanTarget",
			target: &types.ScanTarget{
				OS: &ftypes.OS{Family: "ubuntu", Name: "22.04"},
				Packages: []ftypes.Package{
					{Name: "pkg1", Relationship: ftypes.RelationshipDirect},
				},
				Applications: []ftypes.Application{
					{
						Type: ftypes.Composer,
						Packages: []ftypes.Package{
							{Name: "lib1", Relationship: ftypes.RelationshipDirect},
						},
					},
				},
				Misconfigurations: []ftypes.Misconfiguration{
					{Type: "Kubernetes", ID: "AVD-KSV-0001"},
				},
			},
			options: types.ScanOptions{
				PkgRelationships: []ftypes.Relationship{ftypes.RelationshipIndirect},
			},
			want: &types.ScanTarget{
				OS:       &ftypes.OS{Family: "ubuntu", Name: "22.04"},
				Packages: []ftypes.Package{},
				Applications: []ftypes.Application{
					{
						Type:     ftypes.Composer,
						Packages: []ftypes.Package{},
					},
				},
				Misconfigurations: []ftypes.Misconfiguration{
					{Type: "Kubernetes", ID: "AVD-KSV-0001"},
				},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			excludePackages(tt.target, tt.options)
			if !reflect.DeepEqual(tt.target, tt.want) {
				t.Errorf("excludePackages() = %v, want %v", tt.target, tt.want)
			}
		})
	}
}
