// ********RoostGPT********
/*
Test generated by RoostGPT for test trivy-scan-mock using AI Type Claude AI and AI Model claude-3-5-sonnet-20240620

ROOST_METHOD_HASH=excludeDevDeps_492d994966
ROOST_METHOD_SIG_HASH=excludeDevDeps_ec651cecfd

FUNCTION_DEF=func excludeDevDeps(apps []ftypes.Application, include bool)
Here are several test scenarios for the `excludeDevDeps` function:

```
Scenario 1: Exclude Development Dependencies

Details:
  Description: This test verifies that the function correctly excludes development dependencies when the 'include' flag is set to false.

Execution:
  Arrange:
    - Create a slice of ftypes.Application with a mix of regular and development dependencies.
    - Set the 'include' parameter to false.
  Act:
    - Call excludeDevDeps(apps, false)
  Assert:
    - Verify that all development dependencies are removed from the applications' package lists.
    - Check that regular dependencies remain unchanged.

Validation:
  This test is crucial to ensure that the function correctly filters out development dependencies when requested. It validates the core functionality of the excludeDevDeps function and its ability to modify the input slice in-place.

Scenario 2: Include All Dependencies

Details:
  Description: This test ensures that the function does not modify the applications' package lists when the 'include' flag is set to true.

Execution:
  Arrange:
    - Create a slice of ftypes.Application with a mix of regular and development dependencies.
    - Set the 'include' parameter to true.
  Act:
    - Call excludeDevDeps(apps, true)
  Assert:
    - Verify that all packages, including development dependencies, remain in the applications' package lists.

Validation:
  This test is important to confirm that the function respects the 'include' flag and does not modify the input when all dependencies should be included. It ensures that the early return mechanism works as expected.

Scenario 3: Empty Application List

Details:
  Description: This test checks the function's behavior when given an empty slice of applications.

Execution:
  Arrange:
    - Create an empty slice of ftypes.Application.
    - Set the 'include' parameter to false.
  Act:
    - Call excludeDevDeps(emptyApps, false)
  Assert:
    - Verify that the function doesn't panic or crash.
    - Check that the empty slice remains unchanged.

Validation:
  This test is necessary to ensure that the function handles edge cases gracefully, specifically when there are no applications to process. It validates the robustness of the function against potential nil or empty input.

Scenario 4: Applications with No Packages

Details:
  Description: This test verifies the function's behavior when applications have empty package lists.

Execution:
  Arrange:
    - Create a slice of ftypes.Application where some or all applications have empty Packages slices.
    - Set the 'include' parameter to false.
  Act:
    - Call excludeDevDeps(apps, false)
  Assert:
    - Verify that the function doesn't panic or crash.
    - Check that applications with empty package lists remain unchanged.

Validation:
  This test ensures that the function can handle applications that don't have any packages without errors. It's important for maintaining the integrity of the input data structure even when some applications lack package information.

Scenario 5: Logging Behavior for Excluded Dev Dependencies

Details:
  Description: This test checks if the function logs the appropriate message when excluding development dependencies.

Execution:
  Arrange:
    - Create a slice of ftypes.Application with at least one development dependency.
    - Set up a mock or capture for the log output.
    - Set the 'include' parameter to false.
  Act:
    - Call excludeDevDeps(apps, false)
  Assert:
    - Verify that the log message "Suppressing dependencies for development and testing. To display them, try the '--include-dev-deps' flag." is output exactly once.

Validation:
  This test is important to ensure that the function provides appropriate feedback to the user when excluding development dependencies. It also verifies that the logging occurs only once, regardless of how many development dependencies are excluded.

Scenario 6: Concurrent Access Safety

Details:
  Description: This test verifies that the function behaves correctly when called concurrently from multiple goroutines.

Execution:
  Arrange:
    - Create a large slice of ftypes.Application with a mix of regular and development dependencies.
    - Set up multiple goroutines to call the function simultaneously.
    - Set the 'include' parameter to false for all calls.
  Act:
    - Concurrently call excludeDevDeps(apps, false) from multiple goroutines.
  Assert:
    - Verify that all development dependencies are consistently removed from all applications.
    - Check for any race conditions or unexpected behavior due to concurrent access.

Validation:
  This test is crucial for ensuring thread-safety of the function, especially considering the use of sync.OnceFunc for logging. It validates that the function can be safely used in concurrent environments without data races or inconsistent results.
```

These test scenarios cover various aspects of the `excludeDevDeps` function, including its core functionality, edge cases, error handling, and concurrency considerations. They aim to ensure the function behaves correctly under different conditions and maintains data integrity.
*/

// ********RoostGPT********
package local

import (
	"reflect"
	"testing"

	"github.com/aquasecurity/trivy/pkg/fanal/types"
	"github.com/aquasecurity/trivy/pkg/log"
)

// mockLogger is a simple mock implementation of the logger
type mockLogger struct {
	infoFunc func(msg string)
}

func (m *mockLogger) Info(msg string) {
	if m.infoFunc != nil {
		m.infoFunc(msg)
	}
}

// Implement other logger methods as needed
func (m *mockLogger) Debug(msg string)                          {}
func (m *mockLogger) Warn(msg string)                           {}
func (m *mockLogger) Error(msg string)                          {}
func (m *mockLogger) Fatal(msg string)                          {}
func (m *mockLogger) Debugf(format string, args ...interface{}) {}
func (m *mockLogger) Infof(format string, args ...interface{})  {}
func (m *mockLogger) Warnf(format string, args ...interface{})  {}
func (m *mockLogger) Errorf(format string, args ...interface{}) {}
func (m *mockLogger) Fatalf(format string, args ...interface{}) {}

func TestExcludeDevDeps(t *testing.T) {
	tests := []struct {
		name     string
		apps     []types.Application
		include  bool
		expected []types.Application
	}{
		{
			name: "Exclude development dependencies",
			apps: []types.Application{
				{
					Type: "npm",
					Packages: types.Packages{
						{Name: "regular-pkg", Dev: false},
						{Name: "dev-pkg", Dev: true},
					},
				},
			},
			include: false,
			expected: []types.Application{
				{
					Type: "npm",
					Packages: types.Packages{
						{Name: "regular-pkg", Dev: false},
					},
				},
			},
		},
		{
			name: "Include all dependencies",
			apps: []types.Application{
				{
					Type: "npm",
					Packages: types.Packages{
						{Name: "regular-pkg", Dev: false},
						{Name: "dev-pkg", Dev: true},
					},
				},
			},
			include: true,
			expected: []types.Application{
				{
					Type: "npm",
					Packages: types.Packages{
						{Name: "regular-pkg", Dev: false},
						{Name: "dev-pkg", Dev: true},
					},
				},
			},
		},
		{
			name:     "Empty application list",
			apps:     []types.Application{},
			include:  false,
			expected: []types.Application{},
		},
		{
			name: "Applications with no packages",
			apps: []types.Application{
				{
					Type:     "npm",
					Packages: types.Packages{},
				},
			},
			include: false,
			expected: []types.Application{
				{
					Type:     "npm",
					Packages: types.Packages{},
				},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Create a copy of the input apps to avoid modifying the original
			appsCopy := make([]types.Application, len(tt.apps))
			copy(appsCopy, tt.apps)

			// Capture log output
			var logOutput string
			mockLog := &mockLogger{
				infoFunc: func(msg string) {
					logOutput = msg
				},
			}

			// Use a custom logger for this test
			originalLogger := log.Logger
			log.Logger = mockLog
			defer func() {
				log.Logger = originalLogger
			}()

			excludeDevDeps(appsCopy, tt.include)

			if !reflect.DeepEqual(appsCopy, tt.expected) {
				t.Errorf("excludeDevDeps() = %v, want %v", appsCopy, tt.expected)
			}

			if !tt.include && len(tt.apps) > 0 && len(tt.apps[0].Packages) > 0 {
				expectedLogMsg := "Suppressing dependencies for development and testing. To display them, try the '--include-dev-deps' flag."
				if logOutput != expectedLogMsg {
					t.Errorf("Expected log message: %s, got: %s", expectedLogMsg, logOutput)
				}
			}
		})
	}
}
