// ********RoostGPT********
/*
Test generated by RoostGPT for test trivy-scan-mock using AI Type Claude AI and AI Model claude-3-5-sonnet-20240620

ROOST_METHOD_HASH=excludePackages_d68199d8c7
ROOST_METHOD_SIG_HASH=excludePackages_62917a217c

FUNCTION_DEF=func excludePackages(target *types.ScanTarget, options types.ScanOptions) 
Based on the provided function and context, here are several test scenarios for the `excludePackages` function:

Scenario 1: Exclude Non-Production Packages

Details:
  Description: This test verifies that the function correctly excludes non-production packages when the IncludeDevDeps option is set to false.

Execution:
  Arrange: Create a types.ScanTarget with a mix of production and development dependencies. Set up types.ScanOptions with IncludeDevDeps set to false.
  Act: Call excludePackages(target, options)
  Assert: Verify that the resulting Applications in the target only contain production dependencies.

Validation:
  This test is crucial to ensure that the function correctly filters out development dependencies when they should not be included in the scan. It directly tests the excludeDevDeps functionality.

Scenario 2: Include All Packages

Details:
  Description: This test ensures that when IncludeDevDeps is true, all packages, including development dependencies, are retained.

Execution:
  Arrange: Create a types.ScanTarget with various applications including both production and development dependencies. Set up types.ScanOptions with IncludeDevDeps set to true.
  Act: Call excludePackages(target, options)
  Assert: Confirm that all original packages in the Applications slice remain unchanged.

Validation:
  This test is important to verify that the function respects the IncludeDevDeps flag and doesn't mistakenly exclude packages when all should be included.

Scenario 3: Filter Packages by Relationship

Details:
  Description: This test checks if the function correctly filters packages based on their relationship as defined in the ScanOptions.

Execution:
  Arrange: Set up a types.ScanTarget with various package relationships. Configure types.ScanOptions with specific relationship filters.
  Act: Call excludePackages(target, options)
  Assert: Verify that only packages matching the specified relationships remain in the target.

Validation:
  This test ensures that the filterPkgByRelationship function is called and correctly applied, which is crucial for accurately scoping the vulnerability scan.

Scenario 4: Empty Target Applications

Details:
  Description: This test verifies the function's behavior when the target has no applications.

Execution:
  Arrange: Create a types.ScanTarget with an empty Applications slice. Set up types.ScanOptions with various configurations.
  Act: Call excludePackages(target, options)
  Assert: Confirm that the function doesn't crash and that the Applications slice remains empty.

Validation:
  This edge case test is important to ensure the function handles empty inputs gracefully without causing errors or unexpected behavior.

Scenario 5: Large Number of Packages

Details:
  Description: This test checks the function's performance and correctness when dealing with a large number of packages.

Execution:
  Arrange: Create a types.ScanTarget with a very large number of applications and packages. Set up types.ScanOptions with mixed exclusion criteria.
  Act: Call excludePackages(target, options)
  Assert: Verify that the function completes in a reasonable time and correctly applies the exclusion rules to all packages.

Validation:
  This test is crucial for ensuring the function's scalability and efficiency when dealing with large-scale applications or systems.

Scenario 6: Mixed Package Types and Relationships

Details:
  Description: This test ensures the function correctly handles a diverse set of package types and relationships.

Execution:
  Arrange: Set up a types.ScanTarget with a variety of package types (e.g., OS packages, language-specific packages) and relationships. Configure types.ScanOptions with specific inclusion/exclusion criteria.
  Act: Call excludePackages(target, options)
  Assert: Verify that the resulting Applications in the target correctly reflect the applied filters across all package types and relationships.

Validation:
  This test is important to ensure the function works correctly across different package ecosystems and relationship types, which is crucial for comprehensive vulnerability scanning.

These scenarios cover a range of normal operations, edge cases, and potential error conditions for the `excludePackages` function, ensuring thorough testing of its functionality.
*/

// ********RoostGPT********


package local

import (
	"reflect"
	"testing"
	"github.com/aquasecurity/trivy/pkg/fanal/types"
	"github.com/aquasecurity/trivy/pkg/types"
)







func TestExcludePackages(t *testing.T) {
	tests := []struct {
		name    string
		target  *types.ScanTarget
		options types.ScanOptions
		want    *types.ScanTarget
	}{
		{
			name: "Exclude Non-Production Packages",
			target: &types.ScanTarget{
				Applications: []types.Application{
					{
						Type: "npm",
						Libraries: []types.Package{
							{Name: "prod-pkg", Version: "1.0.0"},
							{Name: "dev-pkg", Version: "1.0.0", Dev: true},
						},
					},
				},
			},
			options: types.ScanOptions{IncludeDevDeps: false},
			want: &types.ScanTarget{
				Applications: []types.Application{
					{
						Type: "npm",
						Libraries: []types.Package{
							{Name: "prod-pkg", Version: "1.0.0"},
						},
					},
				},
			},
		},
		{
			name: "Include All Packages",
			target: &types.ScanTarget{
				Applications: []types.Application{
					{
						Type: "npm",
						Libraries: []types.Package{
							{Name: "prod-pkg", Version: "1.0.0"},
							{Name: "dev-pkg", Version: "1.0.0", Dev: true},
						},
					},
				},
			},
			options: types.ScanOptions{IncludeDevDeps: true},
			want: &types.ScanTarget{
				Applications: []types.Application{
					{
						Type: "npm",
						Libraries: []types.Package{
							{Name: "prod-pkg", Version: "1.0.0"},
							{Name: "dev-pkg", Version: "1.0.0", Dev: true},
						},
					},
				},
			},
		},
		{
			name: "Filter Packages by Relationship",
			target: &types.ScanTarget{
				Applications: []types.Application{
					{
						Type: "npm",
						Libraries: []types.Package{
							{Name: "pkg1", Version: "1.0.0", Relationship: types.RelationshipDirect},
							{Name: "pkg2", Version: "1.0.0", Relationship: types.RelationshipIndirect},
						},
					},
				},
			},
			options: types.ScanOptions{RelationshipTypes: []types.RelationshipType{types.RelationshipDirect}},
			want: &types.ScanTarget{
				Applications: []types.Application{
					{
						Type: "npm",
						Libraries: []types.Package{
							{Name: "pkg1", Version: "1.0.0", Relationship: types.RelationshipDirect},
						},
					},
				},
			},
		},
		{
			name: "Empty Target Applications",
			target: &types.ScanTarget{
				Applications: []types.Application{},
			},
			options: types.ScanOptions{IncludeDevDeps: false},
			want: &types.ScanTarget{
				Applications: []types.Application{},
			},
		},
		{
			name: "Large Number of Packages",
			target: &types.ScanTarget{
				Applications: []types.Application{
					{
						Type:      "npm",
						Libraries: generateLargePackageList(1000),
					},
				},
			},
			options: types.ScanOptions{IncludeDevDeps: false},
			want: &types.ScanTarget{
				Applications: []types.Application{
					{
						Type:      "npm",
						Libraries: generateLargePackageList(500),
					},
				},
			},
		},
		{
			name: "Mixed Package Types and Relationships",
			target: &types.ScanTarget{
				Applications: []types.Application{
					{
						Type: "npm",
						Libraries: []types.Package{
							{Name: "npm-prod", Version: "1.0.0", Relationship: types.RelationshipDirect},
							{Name: "npm-dev", Version: "1.0.0", Dev: true, Relationship: types.RelationshipDirect},
						},
					},
					{
						Type: "pip",
						Libraries: []types.Package{
							{Name: "pip-prod", Version: "1.0.0", Relationship: types.RelationshipIndirect},
							{Name: "pip-dev", Version: "1.0.0", Dev: true, Relationship: types.RelationshipIndirect},
						},
					},
				},
			},
			options: types.ScanOptions{
				IncludeDevDeps:    false,
				RelationshipTypes: []types.RelationshipType{types.RelationshipDirect},
			},
			want: &types.ScanTarget{
				Applications: []types.Application{
					{
						Type: "npm",
						Libraries: []types.Package{
							{Name: "npm-prod", Version: "1.0.0", Relationship: types.RelationshipDirect},
						},
					},
					{
						Type:      "pip",
						Libraries: []types.Package{},
					},
				},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			excludePackages(tt.target, tt.options)
			if !reflect.DeepEqual(tt.target, tt.want) {
				t.Errorf("excludePackages() = %v, want %v", tt.target, tt.want)
			}
		})
	}
}
func generateLargePackageList(count int) []types.Package {
	packages := make([]types.Package, count)
	for i := 0; i < count; i++ {
		isDev := i%2 == 0
		packages[i] = types.Package{
			Name:    fmt.Sprintf("package-%d", i),
			Version: "1.0.0",
			Dev:     isDev,
		}
	}
	return packages
}
