// ********RoostGPT********
/*
Test generated by RoostGPT for test trivy-scan-mock using AI Type Claude AI and AI Model claude-3-5-sonnet-20240620

ROOST_METHOD_HASH=excludeDevDeps_492d994966
ROOST_METHOD_SIG_HASH=excludeDevDeps_ec651cecfd

FUNCTION_DEF=func excludeDevDeps(apps []ftypes.Application, include bool) 
Based on the provided function `excludeDevDeps` and the context given, here are several test scenarios:

```
Scenario 1: Exclude Development Dependencies When Include Flag is False

Details:
  Description: This test verifies that when the include flag is set to false, the function correctly excludes packages marked as development dependencies from the applications list.

Execution:
  Arrange: 
    - Create a slice of ftypes.Application with multiple applications.
    - Each application should have a mix of regular and development packages.
  Act: 
    - Call excludeDevDeps(apps, false)
  Assert:
    - Verify that each application in the slice no longer contains packages where Dev is true.
    - Check that the total number of packages across all applications has decreased.

Validation:
  This test is crucial as it verifies the core functionality of the function when development dependencies should be excluded. It ensures that the filtering logic works correctly across multiple applications.

Scenario 2: Retain All Dependencies When Include Flag is True

Details:
  Description: This test ensures that when the include flag is set to true, the function does not modify the applications list, retaining all packages including development dependencies.

Execution:
  Arrange:
    - Create a slice of ftypes.Application with multiple applications.
    - Each application should have a mix of regular and development packages.
  Act:
    - Call excludeDevDeps(apps, true)
  Assert:
    - Verify that the applications slice remains unchanged.
    - Confirm that all packages, including those with Dev set to true, are still present.

Validation:
  This test is important to verify that the function respects the include flag and doesn't modify the data when all dependencies should be retained.

Scenario 3: Handle Empty Applications List

Details:
  Description: This test checks the function's behavior when given an empty slice of applications, ensuring it doesn't cause any errors.

Execution:
  Arrange:
    - Create an empty slice of ftypes.Application.
  Act:
    - Call excludeDevDeps(emptyApps, false)
  Assert:
    - Verify that the function doesn't panic or cause any errors.
    - Confirm that the empty slice remains empty after the function call.

Validation:
  This edge case test is important to ensure the function gracefully handles empty input without causing runtime errors.

Scenario 4: Verify Logging Behavior for Excluded Dependencies

Details:
  Description: This test checks if the logging message is displayed only once when excluding development dependencies, regardless of how many are excluded.

Execution:
  Arrange:
    - Create a slice of ftypes.Application with multiple applications, each containing several development packages.
    - Set up a mock or capture for the log.Info function.
  Act:
    - Call excludeDevDeps(apps, false)
  Assert:
    - Verify that the log.Info function is called exactly once with the message "Suppressing dependencies for development and testing. To display them, try the '--include-dev-deps' flag."

Validation:
  This test is crucial for verifying the correct behavior of the sync.OnceFunc and ensuring that the log message is not spammed when multiple development dependencies are excluded.

Scenario 5: Maintain Non-Development Packages

Details:
  Description: This test ensures that packages not marked as development dependencies are retained in the applications list when excluding development dependencies.

Execution:
  Arrange:
    - Create a slice of ftypes.Application with a mix of development and non-development packages.
  Act:
    - Call excludeDevDeps(apps, false)
  Assert:
    - Verify that all packages where Dev is false are still present in each application.
    - Confirm that the number and details of non-development packages remain unchanged.

Validation:
  This test is important to ensure that the function only removes development dependencies and doesn't affect other packages, maintaining the integrity of the application's required dependencies.
```

These test scenarios cover the main functionality, edge cases, and specific behaviors of the `excludeDevDeps` function, ensuring comprehensive test coverage.
*/

// ********RoostGPT********


package local

import (
	"reflect"
	"testing"
	ftypes "github.com/aquasecurity/trivy/pkg/fanal/types"
	"github.com/aquasecurity/trivy/pkg/log"
)







func (m *mockLogger) Debug(msg string, fields ...interface{}) {}
func (m *mockLogger) Error(msg string, fields ...interface{}) {}
func (m *mockLogger) Fatal(msg string, fields ...interface{}) {}
func (m *mockLogger) Info(msg string, fields ...interface{}) {
	if m.infoFunc != nil {
		m.infoFunc(msg, fields...)
	}
}
func TestExcludeDevDeps(t *testing.T) {
	tests := []struct {
		name     string
		apps     []ftypes.Application
		include  bool
		expected []ftypes.Application
	}{
		{
			name: "Exclude Development Dependencies When Include Flag is False",
			apps: []ftypes.Application{
				{
					Type: "npm",
					Packages: []ftypes.Package{
						{Name: "pkg1", Version: "1.0.0", Dev: false},
						{Name: "pkg2", Version: "2.0.0", Dev: true},
						{Name: "pkg3", Version: "3.0.0", Dev: false},
					},
				},
				{
					Type: "pip",
					Packages: []ftypes.Package{
						{Name: "pkg4", Version: "4.0.0", Dev: true},
						{Name: "pkg5", Version: "5.0.0", Dev: false},
					},
				},
			},
			include: false,
			expected: []ftypes.Application{
				{
					Type: "npm",
					Packages: []ftypes.Package{
						{Name: "pkg1", Version: "1.0.0", Dev: false},
						{Name: "pkg3", Version: "3.0.0", Dev: false},
					},
				},
				{
					Type: "pip",
					Packages: []ftypes.Package{
						{Name: "pkg5", Version: "5.0.0", Dev: false},
					},
				},
			},
		},
		{
			name: "Retain All Dependencies When Include Flag is True",
			apps: []ftypes.Application{
				{
					Type: "npm",
					Packages: []ftypes.Package{
						{Name: "pkg1", Version: "1.0.0", Dev: false},
						{Name: "pkg2", Version: "2.0.0", Dev: true},
					},
				},
			},
			include: true,
			expected: []ftypes.Application{
				{
					Type: "npm",
					Packages: []ftypes.Package{
						{Name: "pkg1", Version: "1.0.0", Dev: false},
						{Name: "pkg2", Version: "2.0.0", Dev: true},
					},
				},
			},
		},
		{
			name:     "Handle Empty Applications List",
			apps:     []ftypes.Application{},
			include:  false,
			expected: []ftypes.Application{},
		},
		{
			name: "Maintain Non-Development Packages",
			apps: []ftypes.Application{
				{
					Type: "npm",
					Packages: []ftypes.Package{
						{Name: "pkg1", Version: "1.0.0", Dev: false},
						{Name: "pkg2", Version: "2.0.0", Dev: true},
						{Name: "pkg3", Version: "3.0.0", Dev: false},
					},
				},
			},
			include: false,
			expected: []ftypes.Application{
				{
					Type: "npm",
					Packages: []ftypes.Package{
						{Name: "pkg1", Version: "1.0.0", Dev: false},
						{Name: "pkg3", Version: "3.0.0", Dev: false},
					},
				},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {

			appsCopy := make([]ftypes.Application, len(tt.apps))
			copy(appsCopy, tt.apps)

			var logMessage string
			log.Logger = &mockLogger{
				infoFunc: func(msg string, fields ...interface{}) {
					logMessage = msg
				},
			}

			excludeDevDeps(appsCopy, tt.include)

			if !reflect.DeepEqual(appsCopy, tt.expected) {
				t.Errorf("excludeDevDeps() = %v, want %v", appsCopy, tt.expected)
			}

			if !tt.include && len(tt.apps) > 0 && len(tt.apps[0].Packages) > len(tt.expected[0].Packages) {
				expectedLogMessage := "Suppressing dependencies for development and testing. To display them, try the '--include-dev-deps' flag."
				if logMessage != expectedLogMessage {
					t.Errorf("Incorrect log message. Got: %s, Want: %s", logMessage, expectedLogMessage)
				}
			}
		})
	}
}
func (m *mockLogger) Warn(msg string, fields ...interface{}) {}
