// ********RoostGPT********
/*
Test generated by RoostGPT for test trivy-scan-mock using AI Type Claude AI and AI Model claude-3-5-sonnet-20240620

ROOST_METHOD_HASH=excludeDevDeps_492d994966
ROOST_METHOD_SIG_HASH=excludeDevDeps_ec651cecfd

FUNCTION_DEF=func excludeDevDeps(apps []ftypes.Application, include bool) 
Based on the provided function `excludeDevDeps` and the context given, here are several test scenarios:

```
Scenario 1: Exclude Development Dependencies

Details:
  Description: This test verifies that the function correctly excludes development dependencies when the 'include' flag is set to false.

Execution:
  Arrange: 
    - Create a slice of ftypes.Application with a mix of regular and development dependencies.
    - Set the 'include' parameter to false.
  Act: 
    - Call excludeDevDeps(apps, false)
  Assert: 
    - Verify that the resulting applications only contain non-development packages.
    - Check that the number of packages in each application has decreased appropriately.

Validation:
  This test is crucial to ensure that the main functionality of excluding development dependencies works as expected. It directly impacts the security scanning process by focusing on production dependencies.

Scenario 2: Include All Dependencies

Details:
  Description: This test ensures that all dependencies, including development ones, are retained when the 'include' flag is set to true.

Execution:
  Arrange: 
    - Create a slice of ftypes.Application with a mix of regular and development dependencies.
    - Set the 'include' parameter to true.
  Act: 
    - Call excludeDevDeps(apps, true)
  Assert: 
    - Verify that the resulting applications contain all original packages, including development dependencies.
    - Check that the number of packages in each application remains unchanged.

Validation:
  This test is important to confirm that the function respects the 'include' flag and doesn't modify the input when all dependencies should be included.

Scenario 3: Empty Application List

Details:
  Description: This test checks the behavior of the function when given an empty list of applications.

Execution:
  Arrange: 
    - Create an empty slice of ftypes.Application.
    - Set the 'include' parameter to false.
  Act: 
    - Call excludeDevDeps(apps, false)
  Assert: 
    - Verify that the function doesn't panic or crash.
    - Check that the resulting slice is still empty.

Validation:
  This edge case test ensures that the function handles empty inputs gracefully, which is important for robustness and error prevention.

Scenario 4: Applications with No Packages

Details:
  Description: This test verifies the function's behavior when applications have no packages.

Execution:
  Arrange: 
    - Create a slice of ftypes.Application where some or all applications have empty Packages slices.
    - Set the 'include' parameter to false.
  Act: 
    - Call excludeDevDeps(apps, false)
  Assert: 
    - Verify that the function doesn't modify applications with no packages.
    - Check that no errors or panics occur.

Validation:
  This test ensures that the function can handle applications without any packages, which might occur in real-world scenarios.

Scenario 5: All Development Dependencies

Details:
  Description: This test checks the function's behavior when all packages in an application are marked as development dependencies.

Execution:
  Arrange: 
    - Create a slice of ftypes.Application where one or more applications have only development packages.
    - Set the 'include' parameter to false.
  Act: 
    - Call excludeDevDeps(apps, false)
  Assert: 
    - Verify that applications with only development dependencies end up with empty package lists.
    - Check that the applications themselves are not removed from the slice.

Validation:
  This test is important to ensure that the function correctly handles the extreme case where all packages might be excluded, leaving an application with no packages.

Scenario 6: Logging Behavior

Details:
  Description: This test verifies that the function logs the appropriate message when excluding development dependencies.

Execution:
  Arrange: 
    - Create a slice of ftypes.Application with at least one development dependency.
    - Set up a mock or capture for the log output.
    - Set the 'include' parameter to false.
  Act: 
    - Call excludeDevDeps(apps, false)
  Assert: 
    - Verify that the log message "Suppressing dependencies for development and testing. To display them, try the '--include-dev-deps' flag." is output exactly once.

Validation:
  This test ensures that the function provides appropriate feedback to users about the exclusion of development dependencies, which is important for usability and transparency.

Scenario 7: Concurrent Access Safety

Details:
  Description: This test checks if the function behaves correctly when called concurrently from multiple goroutines.

Execution:
  Arrange: 
    - Create a large slice of ftypes.Application with a mix of regular and development dependencies.
    - Set up multiple goroutines to call the function simultaneously.
    - Set the 'include' parameter to false.
  Act: 
    - Call excludeDevDeps(apps, false) from multiple goroutines.
  Assert: 
    - Verify that all calls complete without race conditions or data corruption.
    - Check that the final state of the applications is consistent and correct.

Validation:
  This test is crucial for ensuring thread-safety, especially given the use of sync.OnceFunc in the implementation. It validates that the function can be safely used in concurrent environments.
```

These test scenarios cover a range of normal operations, edge cases, and specific behaviors of the `excludeDevDeps` function. They address various aspects including functionality, error handling, and concurrency, providing a comprehensive test suite for the given function.
*/

// ********RoostGPT********


package local

import (
	"reflect"
	"sync"
	"testing"
	ftypes "github.com/aquasecurity/trivy/pkg/fanal/types"
	"github.com/aquasecurity/trivy/pkg/log"
)







func TestExcludeDevDeps(t *testing.T) {
	tests := []struct {
		name     string
		apps     []ftypes.Application
		include  bool
		expected []ftypes.Application
	}{
		{
			name: "Exclude Development Dependencies",
			apps: []ftypes.Application{
				{
					Type: "npm",
					Packages: []ftypes.Package{
						{Name: "prod-pkg", Dev: false},
						{Name: "dev-pkg", Dev: true},
					},
				},
			},
			include: false,
			expected: []ftypes.Application{
				{
					Type: "npm",
					Packages: []ftypes.Package{
						{Name: "prod-pkg", Dev: false},
					},
				},
			},
		},
		{
			name: "Include All Dependencies",
			apps: []ftypes.Application{
				{
					Type: "npm",
					Packages: []ftypes.Package{
						{Name: "prod-pkg", Dev: false},
						{Name: "dev-pkg", Dev: true},
					},
				},
			},
			include: true,
			expected: []ftypes.Application{
				{
					Type: "npm",
					Packages: []ftypes.Package{
						{Name: "prod-pkg", Dev: false},
						{Name: "dev-pkg", Dev: true},
					},
				},
			},
		},
		{
			name:     "Empty Application List",
			apps:     []ftypes.Application{},
			include:  false,
			expected: []ftypes.Application{},
		},
		{
			name: "Applications with No Packages",
			apps: []ftypes.Application{
				{Type: "npm", Packages: []ftypes.Package{}},
			},
			include: false,
			expected: []ftypes.Application{
				{Type: "npm", Packages: []ftypes.Package{}},
			},
		},
		{
			name: "All Development Dependencies",
			apps: []ftypes.Application{
				{
					Type: "npm",
					Packages: []ftypes.Package{
						{Name: "dev-pkg1", Dev: true},
						{Name: "dev-pkg2", Dev: true},
					},
				},
			},
			include: false,
			expected: []ftypes.Application{
				{
					Type:     "npm",
					Packages: []ftypes.Package{},
				},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {

			inputApps := make([]ftypes.Application, len(tt.apps))
			copy(inputApps, tt.apps)

			originalLogInfo := log.Info
			logCalled := false
			log.Info = func(msg string, args ...any) {
				logCalled = true
			}
			defer func() { log.Info = originalLogInfo }()

			excludeDevDeps(inputApps, tt.include)

			if !reflect.DeepEqual(inputApps, tt.expected) {
				t.Errorf("excludeDevDeps() = %v, want %v", inputApps, tt.expected)
			}

			if !tt.include && len(tt.apps) > 0 && len(tt.apps[0].Packages) > 0 && tt.apps[0].Packages[0].Dev {
				if !logCalled {
					t.Error("Expected log message was not called")
				}
			}
		})
	}
}
func TestExcludeDevDepsConcurrent(t *testing.T) {
	apps := []ftypes.Application{
		{
			Type: "npm",
			Packages: []ftypes.Package{
				{Name: "prod-pkg1", Dev: false},
				{Name: "dev-pkg1", Dev: true},
				{Name: "prod-pkg2", Dev: false},
				{Name: "dev-pkg2", Dev: true},
			},
		},
		{
			Type: "pip",
			Packages: []ftypes.Package{
				{Name: "prod-pkg3", Dev: false},
				{Name: "dev-pkg3", Dev: true},
				{Name: "prod-pkg4", Dev: false},
				{Name: "dev-pkg4", Dev: true},
			},
		},
	}

	expected := []ftypes.Application{
		{
			Type: "npm",
			Packages: []ftypes.Package{
				{Name: "prod-pkg1", Dev: false},
				{Name: "prod-pkg2", Dev: false},
			},
		},
		{
			Type: "pip",
			Packages: []ftypes.Package{
				{Name: "prod-pkg3", Dev: false},
				{Name: "prod-pkg4", Dev: false},
			},
		},
	}

	var wg sync.WaitGroup
	for i := 0; i < 10; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			excludeDevDeps(apps, false)
		}()
	}
	wg.Wait()

	if !reflect.DeepEqual(apps, expected) {
		t.Errorf("Concurrent excludeDevDeps() resulted in unexpected state: got %v, want %v", apps, expected)
	}
}
